from datetime import datetime
from pathlib import Path

from app.config import get_settings
from app.models.models import Finding, Scan, Target
from app.utils.logging import get_logger

logger = get_logger(__name__)
settings = get_settings()

def generate_markdown_report(
    scan: Scan,
    target: Target,
    findings: list[Finding],
    prioritized_endpoints: list[dict],
    orchestration_plan: list[dict],
) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Security Assessment Report",
        f"",
        f"**Target:** `{target.domain}`  ",
        f"**Scan ID:** `{scan.id}`  ",
        f"**Status:** {scan.status.value}  ",
        f"**Generated:** {now}  ",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
    ]

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        if not f.false_positive:
            severity_counts[f.severity.value] = severity_counts.get(f.severity.value, 0) + 1

    for sev, count in severity_counts.items():
        lines.append(f"| {sev.capitalize()} | {count} |")

    lines += [
        f"",
        f"**Assets Discovered:** {scan.assets_found}  ",
        f"**Prioritized Endpoints:** {len(prioritized_endpoints)}  ",
        f"",
        f"---",
        f"",
        f"## Findings",
        f"",
    ]

    for f in findings:
        if f.false_positive:
            continue
        lines += [
            f"### [{f.severity.value.upper()}] {f.title}",
            f"",
            f"- **Category:** `{f.category.value}`",
            f"- **Template:** `{f.template_id or 'N/A'}`",
            f"- **URL:** `{f.url or 'N/A'}`",
        ]
        if f.parameter:
            lines.append(f"- **Parameter:** `{f.parameter}`")
        if f.description:
            lines += [f"", f"{f.description}"]
        if f.analyst_notes:
            lines += [f"", f"**Analyst Notes:** {f.analyst_notes}"]
        lines += ["", "---", ""]

    lines += [f"## Prioritized Attack Surface", f""]
    for ap in prioritized_endpoints[:50]:
        lines += [
            f"### {ap.get('url', 'unknown')}",
            f"",
            f"**Risk:** {ap.get('risk_level', 'low')} ({ap.get('risk_score', 0)})",
            f"",
            f"**Category:** {ap.get('category', 'general')}",
        ]
        lines += ["", "---", ""]
    lines += [f"## Orchestration Plan", ""]
    for item in orchestration_plan[:50]:
        lines.append(f"- `{item.get('url')}` => `{','.join(item.get('tasks', [])) or item.get('mode', 'light')}`")

    lines += [
        f"",
        f"*Report generated by Bug Bounty Platform. For authorized use only.*",
    ]
    return "\n".join(lines)


def generate_json_report(
    scan: Scan,
    target: Target,
    findings: list[Finding],
    prioritized_endpoints: list[dict],
    orchestration_plan: list[dict],
) -> dict:
    return {
        "report_version": "1.0",
        "generated_at": datetime.utcnow().isoformat(),
        "scan": {
            "id": scan.id,
            "status": scan.status.value,
            "started_at": scan.started_at.isoformat() if scan.started_at else None,
            "completed_at": scan.completed_at.isoformat() if scan.completed_at else None,
        },
        "target": {
            "id": target.id,
            "domain": target.domain,
        },
        "summary": {
            "assets": scan.assets_found,
            "findings": len([f for f in findings if not f.false_positive]),
            "prioritized_endpoints": len(prioritized_endpoints),
        },
        "findings": [
            {
                "id": f.id,
                "title": f.title,
                "severity": f.severity.value,
                "category": f.category.value,
                "url": f.url,
                "parameter": f.parameter,
                "description": f.description,
                "template_id": f.template_id,
                "is_validated": f.is_validated,
                "false_positive": f.false_positive,
                "analyst_notes": f.analyst_notes,
            }
            for f in findings if not f.false_positive
        ],
        "prioritized_endpoints": prioritized_endpoints,
        "orchestration_plan": orchestration_plan,
    }


def save_report(scan_id: str, content: str | dict, fmt: str) -> str:
    """
    Save a report to disk and return the file path.

    Args:
        scan_id: Scan UUID.
        content: Report content string.
        fmt: Format string: "markdown", "json", "html".

    Returns:
        Absolute path to saved file.
    """
    ext_map = {"markdown": "md", "json": "json", "html": "html"}
    ext = ext_map.get(fmt, "txt")
    reports_dir = Path(settings.reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"report_{scan_id}.{ext}"
    if isinstance(content, dict):
        path.write_text(__import__("json").dumps(content, indent=2), encoding="utf-8")
    else:
        path.write_text(content, encoding="utf-8")
    logger.info("Report saved", path=str(path), format=fmt)
    return str(path)
